### ISSUE TITLE
Add option in Settings to disable "I have written down my derivation path" and entering PIN

### ISSUE THREAD

**Issue by laboon** [novasamatech/parity-signer#2404]
Currently when adding new derivation paths, one needs to enter one's PIN for each derivation path and also verify that one has written down the derivation path for each one.

The PIN has already been entered to start the program, so why do I need to type it in again for _each_ derivation path?

This may not seem like an issue when entering one or two derivation paths, but when one has many derivation paths, it dramatically slows down entering them into the wallet. 

There should be a "I understand what I am doing" settting that allows me to turn off these unnecessary reminders/confirmations. Alternatively, after confirming, there could be an option to not show this message or request a PIN for the next 15 minutes.

**Comment by krodak** [comment]
Pin request is result of security requirement to check for proper device access control when saving new key, as all keys are protected in this way, there is no possibility to add an option to skip this via Settings, as this would mean that these keys would be saved without that protection, which is no go.

On PIN timing, unfortunately on iOS there is no technical possibility to delay pincode request when accessing saved items from Keychain.
